= Hawkular Services Docker Distribution

ifdef::env-github[]
image:https://images.microbadger.com/badges/version/hawkular/hawkular-services.svg["Latest Released Version",link="https://microbadger.com/images/hawkular/hawkular-services"]
image:https://images.microbadger.com/badges/image/hawkular/hawkular-services.svg["Layers and Size Info",link="https://microbadger.com/images/hawkular/hawkular-services"]
endif::[]

This module contains the sources to build a Docker container with Hawkular
Services.  Recent builds of the hawkular services container are available
on https://hub.docker.com/r/hawkular/hawkular-services/[Docker Hub]

== Prometheus

(TODO - need to finish this section)
Hawkular Services requires a running Prometheus instance with.

== Building Hawkular Services

The docker-maven-plugin can be used to create a Dockerfile, and add the docker
image to the local registry.

  mvn docker:build

By default, this will create a docker image with the name
"<username>/hawkular-services". Pass in "-Ddocker.repo.name=something"
to change the repo name (e.g. "something/hawkular-services").

  docker images

== Running Hawkular Services

Next, start up the hawkular services container.

  docker run -p8080:8080 `whoami`/hawkular-services

TIP: If you want to use Hawkular Services with SSL try this command:

  docker run -e HAWKULAR_USE_SSL=true -p 8443:8443 `whoami`/hawkular-services
